name: Test Again
favicon: null
layout_spectrum: 0.95473
typography_spectrum: 0.0292576071806252
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#effafe'
    - '#000000'
    - '#b93019'
    - '#e1b979'
    - '#497644'
  brandStrength: 0.9375
  lightness: 0.9664960824884474
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
