name: Test Again
favicon: null
layout_spectrum: 0.6966015056241304
typography_spectrum: 0.0292576071806252
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6995572021696717
  lightness: 0.9664960824884474
  saturation: 0.8978712386451662
  rhythmicContrast: 0.8226155715528876
purpose: []
